<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSL2VGra\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSL2VGra/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSL2VGra.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSL2VGra\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSL2VGra\App_KernelDevDebugContainer([
    'container.build_hash' => 'SL2VGra',
    'container.build_id' => '312e5610',
    'container.build_time' => 1667473325,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSL2VGra');
